### ISSUE TITLE
fix ssh key upload

### ISSUE THREAD

**Issue by jexp** [jexp/jetbrains-heroku-plugin#1]

**Comment by soswow** [comment]
Is this bug about adding new email/keys pairs in configuration windows? Can't use plugin because of this =\

**Comment by jexp** [comment]
Yes, there.
It is/was a bug in the heroku client API which didn't return any keys (although they were uploaded).

You can always upload your keys using your heroku page. I am not sure how windows handles ssh-keys for users? 
Do you have any issues with other plugins e.g. github that uses ssh-keys via the IDE?
