### ISSUE TITLE
heroku plugin fails to add a new application

### ISSUE THREAD

**Issue by robmurtha** [jexp/jetbrains-heroku-plugin#12]
I setup the plugin and installed my api key. I cannot add a new application.

5:26:32 PM RequestFailedException: Error executing action Add Application: Failed to create app statuscode:302 responseBody:You are being redirected.
5:27:00 PM RequestFailedException: Error executing action Add Application: Failed to create app statuscode:302 responseBody:You are being redirected.

**Comment by jexp** [comment]
What version of the plugin are you using?

**Comment by robmurtha** [comment]
0.3.8 I did have a Heroku issue with keys that I was able to resolve and things are looking better. Thanks.

**Comment by jexp** [comment]
Ah great, thanks for the heads up.
