### ISSUE TITLE
 IncompatibleClassChangeError: Found interface git4idea.repo.GitRepository, but class was expected: Found interface git4idea.repo.GitRepository, but class was expected

### ISSUE THREAD

**Issue by phron** [jexp/jetbrains-heroku-plugin#21]
Hello
This error is marked as 'closed' but it seems it not solved.
Running RubyMine 4.5.4 on Windows7, I have this error
 IncompatibleClassChangeError: Found interface git4idea.repo.GitRepository, but class was expected: Found interface git4idea.repo.GitRepository, but class was expected

If I create a new project and DO NOT 'enable VCS' it seems to work but it mentions in red 'Git integration disabled (please enable)
the log message is : "Throwable: Could not retrieve repository for project bidon2 vcsRoot file://C:/Users/asdemoulin/Documents/Work/bidon2"

Then, if I "enable CVS", save project, close and reopen it, the error is back and Heroku tools don't work..
Hope there's a way to solve that

**Comment by jexp** [comment]
Hi All,

Sorry, that it took so long. I fixed the git4idea class change issue which was another API incompatibility between JetBrains product versions. Also fixed issues with changed icon paths.

Cheers Michael

**Comment by davidimoore** [comment]
I don't believe this bug is resolved. I'm getting the following error after confirming my Heroku Key:

Could not retrieve repository for project ProjectName vcsRoot file:///home/david/Projects/ProjectName

Project Name is not the actual name of the project
