### ISSUE TITLE
Error creating Heroku Tool Window

### ISSUE THREAD

**Issue by kimardenmiller** [jexp/jetbrains-heroku-plugin#23]
After using the plugin for a while, it stopped working with:

Rubymine 5:
javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException: Content is not allowed in prolog.]

Rubymine 4:
javax.xml.bind.UnmarshalException
- with linked exception: 
  [org.xml.sax.SAXParseException: Content is not allowed in prolog.] 

Thoughts on why that might be?
# 

This looks like an error for the heroku API could you check the event log and the IDE logs on disk for stack traces and report them on: https://github.com/jexp/jetbrains-heroku-plugin/issues

**Comment by michael4reynolds** [comment]
Same problem here using IntelliJ 12. The heroku plugin works with a new project, but once I reopen the project the _"javax.xml.bind.UnmarshalException"_ comes up and does not go away even after restarting IntelliJ.

**Comment by kimardenmiller** [comment]
Reading your post and thinking about the "reset" option on my pref pane, thought I'd try resetting. Reset did not seem to do anything, but I removed my API key, applied, then put it back. My apps show up, but still the plugin does not work.

Also, there is now a new way to install the plugin? In RM 4, i copied the files into the lib folder in the app package. Now I see a plugin manager in the prefs. Not sure if that has contributed to my issue, as I first installed the old way on RM5 before I saw the plugin mgr. But I think I put all the lib files back and then used the plugin mgr, still the same results.

**Comment by nerakhon** [comment]
I seem to hit the same issue in Webstorm 5, reinstall of plugin does not help. The issue seems to relate to older projects. When you create a new project the plugin works.
![xml-exception](https://f.cloud.github.com/assets/376883/198234/5bcb913e-8054-11e2-8525-a1fe518da25a.png)

**Comment by utgarda** [comment]
Same problem, though the logs are different:

```
> rubymine.sh

Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)
[  22069]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix icon path=/icons/heroku_icon_16.png class=class com.jetbrains.heroku.ui.HerokuToolWindowFactory 
build = RM-129.861
java.lang.NullPointerException
        at com.jetbrains.heroku.service.HerokuApplicationService.getAllAddons(HerokuApplicationService.java:121)
        at com.jetbrains.heroku.ui.HerokuAddonsWindow.createContentPane(HerokuAddonsWindow.java:33)
        at com.jetbrains.heroku.ui.HerokuToolWindow.<init>(HerokuToolWindow.java:40)
```
