### ISSUE TITLE
Error: "null is not an instance of interface git4idea.repo.GitRepository"

### ISSUE THREAD

**Issue by Kozlov-V** [jexp/jetbrains-heroku-plugin#24]
When initiale this plugin i have this error:
"null is not an instance of interface git4idea.repo.GitRepository"
Windos 7 Pro, IntelliJ IDEA 12.4, JDK 1.7.0_09

**Comment by Kozlov-V** [comment]
i nide add git root project

**Comment by rickyPanzer** [comment]
hey could you clarify what you did the fix this? I'm getting the same error :(

**Comment by jrhite** [comment]
+1 same
